# Generated by Django 2.2.16 on 2020-10-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0002_auto_20201021_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='high',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='low',
            field=models.IntegerField(),
        ),
    ]
